---
title: "Data_preparation"
author: "GabiK"
date: '2022-03-29'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# required scripts & libraries
source("./TimeFrame5.R")
library(lubridate)
library(tidyverse)
library(fitdistrplus)
library(scales)
#folder with curtain data when available
path="./data/curtain_data/"
```

```{r merge_split_files}
#due to size limitations on GitHub, the following files were split
df1=read.csv("./data/pseudo_spring_emergence/Baumberge1_pseudo1.csv")
df2=read.csv("./data/pseudo_spring_emergence/Baumberge1_pseudo2.csv")
df_B1=rbind(df1,df2)
write.csv2(df_B1,"./data/pseudo_spring_emergence/Baumberge1_pseudo.csv",
          row.names = F)

df3=read.csv("./data/pseudo_spring_emergence/Trollenhagen_pseudo1.csv")
df4=read.csv("./data/pseudo_spring_emergence/Trollenhagen_pseudo2.csv")
df_TR=rbind(df3,df4)
write.csv2(df_TR,"./data/pseudo_spring_emergence/Trollenhagen_pseudo.csv",
          row.names = F)

df5=read.csv("./data/curtain_data/Eldena1.txt",header=T, sep=";")
df6=read.csv("./data/curtain_data/Eldena2.txt",header=T, sep=";")
df_EL=rbind(df5,df6)
write.csv2(df_EL,"./data/curtain_data/Eldena.txt",
          row.names = F)

df7=read.csv("./data/curtain_data/Eldena_L8_1.txt",header=T, sep=";")
df8=read.csv("./data/curtain_data/Eldena_L8_2.txt",header=T, sep=";")
df_EL8=rbind(df7,df8)
write.csv2(df_EL8,"./data/curtain_data/Eldena_L8.txt",
          row.names = F)

df9=read.csv("./data/curtain_data/Eldena_L16_1.txt",header=T, sep=";")
df10=read.csv("./data/curtain_data/Eldena_L16_2.txt",header=T, sep=";")
df_EL16=rbind(df9,df10)
write.csv2(df_EL8,"./data/curtain_data/Eldena_L16.txt",
          row.names = F)
```

```{r outlier_detection}
# Example: outlier night in Friedland 28 March 2021 based on curtain data
d=read.csv(paste0(path,"Friedland.txt"), header=TRUE, sep=";")
head(d)
d$Datum=as.Date(d$Datum, tryFormats=c("%d.%m.%Y"))

### create PSEUDODAYS - 12 AM to 12 AM
d$EventSec=to.second(as.character(d$Uhrzeit))
d$pseudodate=ifelse(d$EventSec>43200,as.character(d$Datum),
                      as.character(d$Datum-1))
d$pseudodate=as.Date(d$pseudodate)
head(d)

df=d %>% 
  filter(pseudodate > "2021-01-01" & pseudodate < "2021-05-01") %>% 
  filter(Event== "LS1 Ausflug" |
           Event== "LS1 Einflug" |
           Event==  "LS1 EStatus 0"|
           Event==  "LS1 EStatus 1"|
           Event==  "LS1 EStatus 2"|
           Event==  "LS1 EStatus 3") %>% 
  dplyr::select(pseudodate, Uhrzeit,Event) %>% 
  group_by(pseudodate) %>% 
  count(group=Event== "LS1 Ausflug" |
          Event== "LS1 Einflug") %>% 
  spread(value=n, key=group) %>% 
  rename("curtain"=`FALSE`, "passes"=`TRUE`) %>% 
  mutate(ratio=curtain/passes, na.rm=T)

#curtain registrations over time
df %>% 
  ggplot(aes(x=pseudodate, y=curtain))+
  geom_line() +
  labs(y='curtain registrations', 
       x='')+
  ggtitle("Friedland 2021")+
  #outlier night
  geom_vline(xintercept = as.Date("2021-03-27"), col="red")+
  geom_vline(xintercept = as.Date("2021-03-29"), col="red")+
  theme_bw()+
  scale_y_continuous(labels = comma_format())+
  scale_x_date(breaks="2 weeks", date_labels = "%b %d")+
   theme(plot.title = element_text(hjust = 0.5))

ggsave(paste0("./accuracy/output/Friedland_curtain_outlier.png"),
       width =18, height =12, dpi = 800, units = "cm", device='png')

hist(df$curtain)
fit.gamma <- fitdist(df$curtain/10, distr = "gamma", method = "mle")

summary(fit.gamma)
plot(fit.gamma)

png(filename="./accuracy/output/Friedland_curtain_gamm_dist.png")
plot(fit.gamma)
dev.off()
```

