---
title: "IR_sites_plots"
author: "GabiK"
date: '2022-03-31'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
```

```{r data}
#winter count data
wc=read.csv("./data/winter_counts.csv")
head(wc)
#site names for the plot
sites=c(`Anklam`="Anklam\n (2021)",
        `Demmin`="Demmin\n (2021)", 
        `Friedland`="Friedland\n (2021)",
        `Peenemuende`="Peenemünde\n (2021)",
        `Eldena`="Eldena\n (2021)")
#breaks on y axis
breaks_y=c(100,150,200,300,400)

confidence_intervals=read.csv("./accuracy/output/site_specific_CI_IRsites.csv")
confidence_intervals$Site=as.character(confidence_intervals$Site)
confidence_intervals=confidence_intervals[1:5,]


vid=read.csv("./accuracy/output/video_CI_IRsites.csv")
vid$Site=as.character(vid$Site)
vid=subset(vid,vid$Site!="Eldena_L16")
vid$Site=c("Anklam","Peenemuende","Friedland","Demmin","Eldena")

confidence_intervals_adj=read.csv("./accuracy/output/extrapolated_CI_IRsites.csv")
confidence_intervals_adj$Site=as.character(confidence_intervals_adj$Site)
confidence_intervals_adj=confidence_intervals_adj[1:5,]

confidence_intervals$year=as.numeric(confidence_intervals$year)
wc$year=as.numeric(wc$year)
confidence_intervals_adj$year=as.numeric(confidence_intervals_adj$year)
vid$year=as.numeric(vid$year)

df=inner_join(confidence_intervals,wc, by=c("Site","year")) 

df1=inner_join(df,confidence_intervals_adj, by=c("Site","year")) 
df1$year=as.numeric(df1$year)
df2=inner_join(df1,vid, by=c("Site","year")) %>% 
  gather(type,value,-Site,-year) %>% 
  filter(type=="LB.x" | type=="LB.y"| type=="WC" | type=="VID")
df2

#ANK, PEN, FRD, DEM, ELD
#LB,WC,VID
df2$lcl=c(confidence_intervals$lcl,rep(NA,5),
          confidence_intervals_adj$lcl,vid$lcl)

df2$ucl=c(confidence_intervals$ucl,rep(NA,5),
          confidence_intervals_adj$ucl,vid$ucl)

df2$Site = factor(df$Site,
                  levels=c("Anklam","Demmin",
                           "Friedland","Peenemuende", "Eldena"))
df2$type[df2$type == "LB.x"] <- "LBsite"
df2$type[df2$type == "LB.y"] <- "LBext"

df2$type=as.factor(df2$type)

df2$type=factor(df2$type, levels=c("LBsite","LBext", "VID", "WC"))

df2$value=as.numeric(df2$value)
df2$lcl=as.numeric(df2$lcl)
df2$ucl=as.numeric(df2$ucl)
```

```{r plot}
legendlabels=c(expression('Light barrier-based population size \n estimate with site-specific CI'),
               expression('Light barrier-based population size \n estimate with extrapolated CI'),
               expression("Video-based population \n size estimate"),
               "Winter count"
)

plot_sites=df2 %>%
  ggplot(aes(x=type, y=value))+
  labs(y="population size estimate",
       x="",
       shape=" ",
       color=" ")+
  geom_point(aes(shape = type,col=type), size = 2) +
  geom_errorbar(aes(x = type, ymin = lcl,
                    ymax = ucl, col=type),
                    width=.5, lwd=0.5,  
                show.legend = T)+
  facet_grid(cols = vars(Site),labeller = as_labeller(sites))+
  theme(legend.position = "bottom",
        legend.key.size=unit(1,"cm"),
        legend.text.align = 0,
        legend.text=element_text(size=6),
        legend.key = element_blank(),
        legend.box.spacing=unit(-0.5, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.spacing.x = unit(0.1, "cm"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 6),
        panel.border = element_rect(fill=NA,color="black", size=0.5,
                                    linetype="solid"))+
  scale_y_continuous(breaks=seq(0,800,by=100), expand=c(0,50))+
  scale_colour_discrete(labels = legendlabels,
                        na.value = "grey50")+
  scale_shape_manual(values = c(15,15,16,17),
                     labels = legendlabels)+
  guides(colour=guide_legend(nrow=2), byrow=T)
plot_sites

ggsave(paste0("./accuracy/output/LB_VID_WC_all_IR_sites.png"),
       width = 10, height = 10, dpi = 800, units = "cm", device='png')

```
